{% set name = "mbslave" %}
{% set version = "29.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mbslave-{{ version }}.tar.gz
  sha256: 405e44376f9c05ac4207f7b293f5330eb071d2adaf91854ca828b6f2384371a0
  url: https://github.com/acoustid/{{ name[0] }}/archive/refs/tags/v{{ version }}.tar.gz
  
build:
  entry_points:
    - mbslave = mbslave.replication:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - psycopg2 >=2.9.2,<3.0.0
    - six >=1.16.0,<2.0.0
    - prometheus_client >=0.20.0
  run_constrained:
     - mbdata >=29
     
test:
  imports:
    - mbslave
  commands:
    - pip check
    - mbslave --help
  requires:
    - pip
    - python {{ python_min }}
about:
  summary: MusicBrainz Database Mirror
  license: MIT
  license_file: LICENSE
  home: https://github.com/acoustid/mbslave
  dev_url: https://github.com/acoustid/mbslave

extra:
  recipe-maintainers:
    - HeavyTony2
